In [1]:
import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
BASE_PATH = os.environ.get("BASE_PATH")
time_cols = ['date', 'day_number', 'walmart_year_week', 'month_name', 'weekday']
df_time = pd.read_parquet(f'{BASE_PATH}/data/processed/df_merged.parquet', columns=time_cols)
pd.set_option('display.max_columns', None)
df_time.head()

        date  day_number  walmart_year_week month_name   weekday
0 2011-01-29           1              11101    January  Saturday
1 2011-01-29           1              11101    January  Saturday
2 2011-01-29           1              11101    January  Saturday
3 2011-01-29           1              11101    January  Saturday
4 2011-01-29           1              11101    January  Saturday

In [13]:
df_time.info()

<class 'pandas.DataFrame'>
RangeIndex: 59181090 entries, 0 to 59181089
Data columns (total 5 columns):
 #   Column             Dtype
---  ------             -----
 0   date               datetime64[us]
 1   day_number         int16
 2   walmart_year_week  int32
 3   month_name         category
 4   weekday            category
dtypes: category(2), datetime64[us](1), int16(1), int32(1)
memory usage: 903.0 MB

### Time Features:

In [14]:
df_time.head()

        date  day_number  walmart_year_week month_name   weekday
0 2011-01-29           1              11101    January  Saturday
1 2011-01-29           1              11101    January  Saturday
2 2011-01-29           1              11101    January  Saturday
3 2011-01-29           1              11101    January  Saturday
4 2011-01-29           1              11101    January  Saturday

In [15]:
# Extract Date Features 
df_time['year'] = df_time['date'].dt.year
df_time['month'] = df_time['date'].dt.month
df_time['week'] = df_time['date'].dt.isocalendar().week.astype("int16") 
df_time['day'] = df_time['date'].dt.day
df_time['quarter'] = df_time['date'].dt.quarter
df_time['is_weekend'] = df_time['date'].dt.dayofweek >= 5 # Monday=0, Sunday=6.
df_time['is_month_start'] = df_time['date'].dt.is_month_start
df_time['is_month_end'] = df_time['date'].dt.is_month_end

In [16]:
df_time.head(3)

,date,day_number,walmart_year_week,month_name,weekday,year,month,week,day,quarter,is_weekend,is_month_start,is_month_end
0,2011-01-29,1,11101,January,Saturday,2011,1,4,29,1,True,False,False
1,2011-01-29,1,11101,January,Saturday,2011,1,4,29,1,True,False,False
2,2011-01-29,1,11101,January,Saturday,2011,1,4,29,1,True,False,False

In [17]:
for col in ['year', 'month', 'day', 'quarter']:
    df_time[col] = df_time[col].astype('int16')

In [18]:
df_time.info()

<class 'pandas.DataFrame'>
RangeIndex: 59181090 entries, 0 to 59181089
Data columns (total 13 columns):
 #   Column             Dtype
---  ------             -----
 0   date               datetime64[us]
 1   day_number         int16
 2   walmart_year_week  int32
 3   month_name         category
 4   weekday            category
 5   year               int16
 6   month              int16
 7   week               int16
 8   day                int16
 9   quarter            int16
 10  is_weekend         bool
 11  is_month_start     bool
 12  is_month_end       bool
dtypes: bool(3), category(2), datetime64[us](1), int16(6), int32(1)
memory usage: 1.6 GB

In [19]:
df_time.drop(columns=['date'], inplace=True)
df_time.head().reset_index()

,index,day_number,walmart_year_week,month_name,weekday,year,month,week,day,quarter,is_weekend,is_month_start,is_month_end
0,0,1,11101,January,Saturday,2011,1,4,29,1,True,False,False
1,1,1,11101,January,Saturday,2011,1,4,29,1,True,False,False
2,2,1,11101,January,Saturday,2011,1,4,29,1,True,False,False
3,3,1,11101,January,Saturday,2011,1,4,29,1,True,False,False
4,4,1,11101,January,Saturday,2011,1,4,29,1,True,False,False