In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
BASE_PATH = os.environ.get('BASE_PATH')
calendar = pd.read_csv(f'{BASE_PATH}/data/raw/calendar.csv')
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [28]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 215.5 KB

In [29]:
print(f"Unique Values of Date: {calendar['date'].nunique()}")

calendar['date'].sample(5)

Unique Values of Date: 1969

436     2012-04-09
1561    2015-05-09
1001    2013-10-26
1534    2015-04-12
29      2011-02-27
Name: date, dtype: str

In [30]:
calendar['wm_yr_wk'].nunique()

282

In [31]:
calendar['wm_yr_wk'].astype(str).str.slice(0, 3).value_counts()

wm_yr_wk
113    371
111    364
112    364
114    364
115    364
116    142
Name: count, dtype: int64

In [32]:
calendar['weekday'].value_counts()

weekday
Saturday     282
Sunday       282
Monday       281
Tuesday      281
Wednesday    281
Thursday     281
Friday       281
Name: count, dtype: int64

In [33]:
calendar['wday'].value_counts()

wday
1    282
2    282
3    281
4    281
5    281
6    281
7    281
Name: count, dtype: int64

In [34]:
calendar['month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
calendar['year'].value_counts()

year
2012    366
2013    365
2014    365
2015    365
2011    337
2016    171
Name: count, dtype: int64

In [36]:
calendar['d'].value_counts()

d
d_1       1
d_2       1
d_3       1
d_4       1
d_5       1
         ..
d_1965    1
d_1966    1
d_1967    1
d_1968    1
d_1969    1
Name: count, Length: 1969, dtype: int64

In [37]:
calendar['event_name_1'].unique()

<StringArray>
[                  nan,           'SuperBowl',       'ValentinesDay',
       'PresidentsDay',           'LentStart',           'LentWeek2',
       'StPatricksDay',           'Purim End',      'OrthodoxEaster',
          'Pesach End',       'Cinco De Mayo',        'Mother's day',
         'MemorialDay',      'NBAFinalsStart',        'NBAFinalsEnd',
        'Father's day',     'IndependenceDay',      'Ramadan starts',
         'Eid al-Fitr',            'LaborDay',         'ColumbusDay',
           'Halloween',           'EidAlAdha',         'VeteransDay',
        'Thanksgiving',           'Christmas',        'Chanukah End',
             'NewYear',   'OrthodoxChristmas', 'MartinLutherKingDay',
              'Easter']
Length: 31, dtype: str

In [38]:
calendar['event_type_1'].unique()

<StringArray>
[nan, 'Sporting', 'Cultural', 'National', 'Religious']
Length: 5, dtype: str

In [39]:
calendar['event_name_2'].unique()

<StringArray>
[nan, 'Easter', 'Cinco De Mayo', 'OrthodoxEaster', 'Father's day']
Length: 5, dtype: str

In [40]:
calendar['event_type_2'].unique()

<StringArray>
[nan, 'Cultural', 'Religious']
Length: 3, dtype: str

In [41]:
calendar.loc[calendar['snap_CA'] == 1, ['date', 'snap_CA']]

            date  snap_CA
3     2011-02-01        1
4     2011-02-02        1
5     2011-02-03        1
6     2011-02-04        1
7     2011-02-05        1
...          ...      ...
1955  2016-06-06        1
1956  2016-06-07        1
1957  2016-06-08        1
1958  2016-06-09        1
1959  2016-06-10        1

[650 rows x 2 columns]

In [42]:
calendar['snap_CA'].value_counts()

snap_CA
0    1319
1     650
Name: count, dtype: int64

In [43]:
calendar['snap_TX'].value_counts()

snap_TX
0    1319
1     650
Name: count, dtype: int64

In [44]:
calendar['snap_WI'].value_counts()

snap_WI
0    1319
1     650
Name: count, dtype: int64

In [45]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 215.5 KB

In [46]:
calendar.isna().sum()

date               0
wm_yr_wk           0
weekday            0
wday               0
month              0
year               0
d                  0
event_name_1    1807
event_type_1    1807
event_name_2    1964
event_type_2    1964
snap_CA            0
snap_TX            0
snap_WI            0
dtype: int64

In [47]:
(calendar['event_name_1'].isna().sum() / len(calendar)) * 100

np.float64(91.77247333671914)

In [48]:
(calendar['event_type_2'].isna().sum() / len(calendar)) * 100

np.float64(99.74606399187405)

In [49]:
calendar['date'].duplicated().sum()

np.int64(0)