In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv
load_dotenv()

In [ ]:
BASE_PATH = os.environ.get("BASE_PATH")
calendar = pd.read_csv(f'{BASE_PATH}/data/raw/calendar.csv')
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [3]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 263.1 KB

In [4]:
columns_to_rename = {
    'd' : 'day_number',
    'event_name_1' : 'event_name',
    'event_type_1' : 'event_type',
    'wm_yr_wk' : 'walmart_year_week'
}

calendar.rename(columns=columns_to_rename, inplace=True)
calendar.head()

,date,walmart_year_week,weekday,wday,month,year,day_number,event_name,event_type,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [5]:
calendar['date'] = pd.to_datetime(calendar['date'])

In [6]:
calendar['weekday'].head()

0     Saturday
1       Sunday
2       Monday
3      Tuesday
4    Wednesday
Name: weekday, dtype: str

In [7]:
calendar.drop(columns=['wday'], inplace=True)
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int64
 2   weekday            1969 non-null   str
 3   month              1969 non-null   int64
 4   year               1969 non-null   int64
 5   day_number         1969 non-null   str
 6   event_name         162 non-null    str
 7   event_type         162 non-null    str
 8   event_name_2       5 non-null      str
 9   event_type_2       5 non-null      str
 10  snap_CA            1969 non-null   int64
 11  snap_TX            1969 non-null   int64
 12  snap_WI            1969 non-null   int64
dtypes: datetime64[us](1), int64(6), str(6)
memory usage: 228.5 KB

In [8]:
calendar['walmart_year_week'].nunique()

282

In [9]:
print(calendar['walmart_year_week'].max())
print(calendar['walmart_year_week'].min())

11621
11101

In [ ]:
calendar['walmart_year_week'] = calendar['walmart_year_week'].astype('int32')

In [11]:
calendar.drop(columns=['event_name_2', 'event_type_2'], inplace=True)

In [12]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   str
 3   month              1969 non-null   int64
 4   year               1969 non-null   int64
 5   day_number         1969 non-null   str
 6   event_name         162 non-null    str
 7   event_type         162 non-null    str
 8   snap_CA            1969 non-null   int64
 9   snap_TX            1969 non-null   int64
 10  snap_WI            1969 non-null   int64
dtypes: datetime64[us](1), int16(1), int64(5), str(4)
memory usage: 185.6 KB

In [13]:
months = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}

calendar['month_name'] = calendar['month'].map(months)
calendar.drop(columns=['month'], inplace=True)

In [14]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   str
 3   year               1969 non-null   int64
 4   day_number         1969 non-null   str
 5   event_name         162 non-null    str
 6   event_type         162 non-null    str
 7   snap_CA            1969 non-null   int64
 8   snap_TX            1969 non-null   int64
 9   snap_WI            1969 non-null   int64
 10  month_name         1969 non-null   str
dtypes: datetime64[us](1), int16(1), int64(4), str(5)
memory usage: 197.5 KB

In [15]:
calendar['day_number'].head()

0    d_1
1    d_2
2    d_3
3    d_4
4    d_5
Name: day_number, dtype: str

In [16]:
calendar['day_number'] = calendar['day_number'].str.replace('d_', '')
calendar['day_number'] = calendar['day_number'].astype('int16')

In [17]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   str
 3   year               1969 non-null   int64
 4   day_number         1969 non-null   int16
 5   event_name         162 non-null    str
 6   event_type         162 non-null    str
 7   snap_CA            1969 non-null   int64
 8   snap_TX            1969 non-null   int64
 9   snap_WI            1969 non-null   int64
 10  month_name         1969 non-null   str
dtypes: datetime64[us](1), int16(2), int64(4), str(4)
memory usage: 175.5 KB

In [18]:
cols = ['event_type', 'event_name']
def fill_with_key(df, key, cols):
    for col in cols:
        df[col] = df[col].fillna(key)
    return df

calendar = fill_with_key(calendar,'No Event', cols)
calendar.isna().sum()

date                 0
walmart_year_week    0
weekday              0
year                 0
day_number           0
event_name           0
event_type           0
snap_CA              0
snap_TX              0
snap_WI              0
month_name           0
dtype: int64

In [19]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   str
 3   year               1969 non-null   int64
 4   day_number         1969 non-null   int16
 5   event_name         1969 non-null   str
 6   event_type         1969 non-null   str
 7   snap_CA            1969 non-null   int64
 8   snap_TX            1969 non-null   int64
 9   snap_WI            1969 non-null   int64
 10  month_name         1969 non-null   str
dtypes: datetime64[us](1), int16(2), int64(4), str(4)
memory usage: 203.3 KB

In [20]:
calendar['event_name'].nunique()

31

In [21]:
calendar['event_name'].unique()

<ArrowStringArray>
[           'No Event',           'SuperBowl',       'ValentinesDay',
       'PresidentsDay',           'LentStart',           'LentWeek2',
       'StPatricksDay',           'Purim End',      'OrthodoxEaster',
          'Pesach End',       'Cinco De Mayo',        'Mother's day',
         'MemorialDay',      'NBAFinalsStart',        'NBAFinalsEnd',
        'Father's day',     'IndependenceDay',      'Ramadan starts',
         'Eid al-Fitr',            'LaborDay',         'ColumbusDay',
           'Halloween',           'EidAlAdha',         'VeteransDay',
        'Thanksgiving',           'Christmas',        'Chanukah End',
             'NewYear',   'OrthodoxChristmas', 'MartinLutherKingDay',
              'Easter']
Length: 31, dtype: str

In [22]:
for col in cols: 
    calendar[col] = calendar[col].astype('category')

In [23]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   str
 3   year               1969 non-null   int64
 4   day_number         1969 non-null   int16
 5   event_name         1969 non-null   category
 6   event_type         1969 non-null   category
 7   snap_CA            1969 non-null   int64
 8   snap_TX            1969 non-null   int64
 9   snap_WI            1969 non-null   int64
 10  month_name         1969 non-null   str
dtypes: category(2), datetime64[us](1), int16(2), int64(4), str(2)
memory usage: 145.7 KB

In [24]:
binary_cols = ['snap_CA', 'snap_TX', 'snap_WI']

for col in binary_cols:
    calendar[col] = calendar[col].astype(bool)
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   str
 3   year               1969 non-null   int64
 4   day_number         1969 non-null   int16
 5   event_name         1969 non-null   category
 6   event_type         1969 non-null   category
 7   snap_CA            1969 non-null   bool
 8   snap_TX            1969 non-null   bool
 9   snap_WI            1969 non-null   bool
 10  month_name         1969 non-null   str
dtypes: bool(3), category(2), datetime64[us](1), int16(2), int64(1), str(2)
memory usage: 105.3 KB

In [25]:
calendar['event_type'].unique()

['No Event', 'Sporting', 'Cultural', 'National', 'Religious']
Categories (5, str): ['Cultural', 'National', 'No Event', 'Religious', 'Sporting']

In [26]:
calendar['weekday'] = calendar['weekday'].astype('category')
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   category
 3   year               1969 non-null   int64
 4   day_number         1969 non-null   int16
 5   event_name         1969 non-null   category
 6   event_type         1969 non-null   category
 7   snap_CA            1969 non-null   bool
 8   snap_TX            1969 non-null   bool
 9   snap_WI            1969 non-null   bool
 10  month_name         1969 non-null   str
dtypes: bool(3), category(3), datetime64[us](1), int16(2), int64(1), str(1)
memory usage: 78.2 KB

In [27]:
calendar['month_name'] = calendar['month_name'].astype('category')
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   category
 3   year               1969 non-null   int64
 4   day_number         1969 non-null   int16
 5   event_name         1969 non-null   category
 6   event_type         1969 non-null   category
 7   snap_CA            1969 non-null   bool
 8   snap_TX            1969 non-null   bool
 9   snap_WI            1969 non-null   bool
 10  month_name         1969 non-null   category
dtypes: bool(3), category(4), datetime64[us](1), int16(2), int64(1)
memory usage: 53.0 KB

In [28]:
calendar['year'].value_counts()

year
2012    366
2013    365
2014    365
2015    365
2011    337
2016    171
Name: count, dtype: int64

In [29]:
calendar["date_year"] = calendar["date"].dt.year
calendar['date_year'].value_counts()

date_year
2012    366
2013    365
2014    365
2015    365
2011    337
2016    171
Name: count, dtype: int64

In [30]:
calendar.drop(columns=['date_year', 'year'], inplace=True)
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1969 non-null   datetime64[us]
 1   walmart_year_week  1969 non-null   int16
 2   weekday            1969 non-null   category
 3   day_number         1969 non-null   int16
 4   event_name         1969 non-null   category
 5   event_type         1969 non-null   category
 6   snap_CA            1969 non-null   bool
 7   snap_TX            1969 non-null   bool
 8   snap_WI            1969 non-null   bool
 9   month_name         1969 non-null   category
dtypes: bool(3), category(4), datetime64[us](1), int16(2)
memory usage: 37.6 KB

In [32]:
calendar.head()

,date,walmart_year_week,weekday,day_number,event_name,event_type,snap_CA,snap_TX,snap_WI,month_name
0,2011-01-29,11101,Saturday,1,No Event,No Event,False,False,False,January
1,2011-01-30,11101,Sunday,2,No Event,No Event,False,False,False,January
2,2011-01-31,11101,Monday,3,No Event,No Event,False,False,False,January
3,2011-02-01,11101,Tuesday,4,No Event,No Event,True,True,False,February
4,2011-02-02,11101,Wednesday,5,No Event,No Event,True,False,True,February

In [ ]:
output_path = os.path.join(BASE_PATH, "data", "processed", "calendar_cleaned.parquet") # type: ignore

calendar.to_parquet(output_path, engine="pyarrow", index=False)